{% set name = "MDANSE" %}
{% set version = "2.0.0a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/MDANSE-{{ version }}.tar.gz
  sha256: f796584caa64086ab27fb3cf8ec3c3c7def0965ef1620d1cd6169599ef5b2519

build:
  skip: true  # [py<39]
  entry_points:
    - mdanse = MDANSE.Scripts.mdanse:main
    - mdanse_job = MDANSE.Scripts.mdanse_job:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.9
    - setuptools
    - cython
    - numpy
    - wheel
    - sphinx
    - pip
  run:
    - python >=3.9
    - scipy
    - h5py
    - icecream
    - ase
    - rdkit
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - MDANSE
  commands:
    - pip check
    - mdanse --help
  requires:
    - pip

about:
  summary: MDANSE Core package - Molecular Dynamics trajectory handling and analysis code
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MBartkowiakSTFC
    - ChiCheng45
