{% set name = "MDANSE_GUI" %}
{% set version = "0.1.0a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/MDANSE_GUI-{{ version }}.tar.gz
  sha256: 1a8ef5af4b3cf2c50c22ab32112bf9ef66239198eb326962352b19d56200d2bf

build:
  entry_points:
    - mdanse_elements_database = MDANSE_GUI.Scripts.mdanse_elements_database:main
    - mdanse_gui = MDANSE_GUI.Scripts.mdanse_gui:main
    - mdanse_periodic_table = MDANSE_GUI.Scripts.mdanse_periodic_table:main
    - mdanse_plotter = MDANSE_GUI.Scripts.mdanse_plotter:main
    - mdanse_ud_editor = MDANSE_GUI.Scripts.mdanse_ud_editor:main
    - mdanse_units_editor = MDANSE_GUI.Scripts.mdanse_units_editor:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - numpy
    - wheel
    - sphinx
    - pip
  run:
    - python >=3.9
    - mdanse
    - matplotlib-base
    - qtpy >=5
    - vtk
    - pyqt
    - pyyaml

test:
  imports:
    - MDANSE_GUI
  commands:
    - pip list
  # fails because of vtk and qtpy6
  #  - pip check 
  requires:
    - pip

about:
  home: https://www.isis.stfc.ac.uk/Pages/MDANSEproject.aspx
  summary: MDANSE GUI package - the graphical interface for MDANSE
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MBartkowiakSTFC
    - ChiCheng45
